name: Linux

on: [push, pull_request, workflow_dispatch]

jobs:
  build-gcc:
    runs-on: ubuntu-latest

    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}

    strategy:
      matrix:
        include:
          - cc: gcc-10
            cxx: g++-10
          - cc: gcc-11
            cxx: g++-11
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Install GCC 11
      if: ${{ matrix.cc == 'gcc-11' }}
      run: |
        sudo apt-get update
        sudo apt-get install g++-11 -y

    - name: Print compiler version
      run: ${{ env.CC }} --version

    - name: Install zimg
      run: |
        git clone https://github.com/sekrit-twc/zimg --branch v3.0 --depth 1
        pushd zimg
        ./autogen.sh
        ./configure --prefix=/usr
        make -j2
        sudo make install -j2
        popd
        rm -rf zimg

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        # Version range or exact version of a Python version to use, using SemVer's version range syntax.
        python-version: 3.9

    - name: Install cython
      run: |
        python -m pip install --upgrade pip
        pip install cython

    - name: Set PKG_CONFIG_PATH
      run: echo "PKG_CONFIG_PATH=$pythonLocation/lib/pkgconfig" >> $GITHUB_ENV

    - name: configure
      run: |
        ./autogen.sh
        ./configure --prefix=/usr

    - name: make
      run: | 
        make -j2
        cp -r .libs libs
    
    - name: Upload libs
      if: ${{ matrix.cc == 'gcc-11' }}
      uses: actions/upload-artifact@v4
      with:
        name: libs
        if-no-files-found: error
        path: libs/
    
    - name: Upload includes
      if: ${{ matrix.cc == 'gcc-11' }}
      uses: actions/upload-artifact@v4
      with:
        name: include
        if-no-files-found: error
        path: include/

    - name: make install
      run: |
        sudo make install -j2
        python setup.py install

    - name: Run test
      run: python -m unittest discover -s test -p "*test.py"
    
    
